Update plugin to work with MapboxGL version 0.52.0
jrd/mapbox-gl-mouse-over-event pull request #1
Opened 2019-01-10 15:16 UTC by NicolasMinghetti

2019-01-10 17:24 UTC, jrd requested changes

2019-01-10 17:24 UTC, jrd commented on CHANGELOG.md
> +[1.2.0]: https://github.com/jrd/mapbox-gl-mouse-over-event/compare/v1.1.1...v1.2.0
Ça je trouve ça inutile… (je veux dire cette ligne uniquement)

2019-01-10 17:24 UTC, jrd commented on CHANGELOG.md
> +
On met pas la `1.0.0` et la `1.1.0` ?

2019-01-10 17:24 UTC, jrd commented on index.js
> +    const Event = function Event(type, data) {
Il serait bien d'indiquer que ceci a été copié depuis le code source de mapboxgl car ça n'est pas dispo publiquement dans la lib. Éventuellement avec un lien direct sur le code source sur github.

2019-01-10 17:24 UTC, jrd commented on index.js
> +            for (var k in src) {
`const`
```suggestion
            for (const k in src) {
```

2019-01-10 17:24 UTC, jrd commented on index.js
> +        let sources = [];
```suggestion
        const sources = [];
```

2019-01-10 17:24 UTC, jrd commented on index.js
> +        let len = arguments.length - 1;
```suggestion
        const len = arguments.length - 1;
```

2019-01-10 17:24 UTC, jrd commented on index.js
> +    const Event = function Event(type, data) {
Tu peux ptre condenser un peu le code en enlevant quelques retours chariots.

Et tu peux séparer le code copié de mapboxgl du reste avec un commentaire du type :
```
////////////////////////////////////////////////////////////
```

2019-01-10 17:24 UTC, jrd commented on index.js
>          let listener = layerListener == null ? layerIdOrListener : layerListener;
```suggestion
        const listener = layerListener == null ? layerIdOrListener : layerListener;
```

2019-01-10 17:24 UTC, jrd commented on index.js
> +                return originalMapFireFunc.call(this, event);
Il manque les éventuels arguments contextuels (dans `arguments[1]`)

2019-01-10 17:24 UTC, jrd commented on index.js
> +            return originalMapFireFunc.call(this, event);
Idem plus haut

2019-01-11 10:07 UTC, NicolasMinghetti commented on index.js
> +        let len = arguments.length - 1;
Pas pour celui là, on modifie sa valeur en dessous

2019-01-11 10:10 UTC, NicolasMinghetti commented
All comments resolved

2019-01-11 10:16 UTC, jrd approved these changes

2019-01-11 10:17 UTC, merged